Import the numpy package under the name np

In [1]:
import numpy as np

Create a null vector of size 10

In [2]:
arr1=np.array([])
print(arr1)

[]


Create a vector with values ranging from 10 to 49

In [3]:
arr1=np.array(range(10,50))
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Find the shape of previous array in question 3

In [4]:
arr1.shape

(40,)

Print the type of the previous array in question 3

In [5]:
arr1.dtype

dtype('int64')

Print the dimension of the array in question 3

In [6]:
arr1.ndim

1

Create a boolean array with all the True values

In [7]:
bools=np.array([True,True,True,True,True])
bools

array([ True,  True,  True,  True,  True], dtype=bool)

Create a two dimensional array

In [8]:
arr2d=np.array([[1,2,3,4],[5,6,7,8]])
arr2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Create a three dimensional array

In [9]:
arr3d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Difficulty Level Easy

Reverse a vector (first element becomes last)

In [10]:
temp=arr1[0]
arr1[0]=arr1[arr1.size-1]
arr1[arr1.size-1]=temp
arr1

array([49, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 10])

In [11]:
nullVector=np.array([None]*10)
nullVector[4]=1
nullVector

array([None, None, None, None, 1, None, None, None, None, None], dtype=object)

Create a 3x3 identity matrix

In [12]:
arr3d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr = np.array([1, 2, 3, 4, 5])
arr=arr.astype('float64')
arr

array([ 1.,  2.,  3.,  4.,  5.])

Multiply arr1 with arr2

In [14]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr1*arr2

array([[  0.,   8.,   3.],
       [ 28.,  10.,  72.]])

Make an array by comparing both the arrays provided above

In [15]:
arr1==arr2

array([[False, False, False],
       [False, False, False]], dtype=bool)

Extract all odd numbers from arr with values(0-9)

In [16]:
old=arr[arr%2!=0]
old

array([ 1.,  3.,  5.])

Replace all odd numbers to -1 from previous array

In [17]:
old=(arr%2!=0)
arr[old]=-1
arr

array([-1.,  2., -1.,  4., -1.])

Replace the values of indexes 5,6,7 and 8 to 12

In [18]:
arr = np.arange(10)
arr[4:8]=12
arr

array([ 0,  1,  2,  3, 12, 12, 12, 12,  8,  9])

Create a 2d array with 1 on the border and 0 inside

In [19]:
arr1.shape


(2, 3)

In [20]:
t=arr1.shape
t[0]
arr1[0:t[0],1:t[1]-1]=0
arr1[0:t[0],0:1]=1
arr1[0:t[0],t[1]-1:t[1]]=1
arr1

array([[ 1.,  0.,  1.],
       [ 1.,  0.,  1.]])

# Difficulty Level Medium

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[1][1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

Convert all the values of 1st array to 64

In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0][0:2][0:2,0:1]=64
arr3d[1][0:2][0:2,0:1]=64
arr3d


array([[[64,  2,  3],
        [64,  5,  6]],

       [[64,  8,  9],
        [64, 11, 12]]])

Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
arr2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2d[0]

array([0, 1, 2, 3, 4])

Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
arr2d[1]

array([5, 6, 7, 8, 9])

Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
arr2d[0:2,3:4]

array([[3],
       [8]])

Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
arr10d=np.random.rand(10,10)
arr10d

array([[ 0.01514031,  0.68294972,  0.86162145,  0.51287542,  0.84215349,
         0.62006367,  0.91660377,  0.0870126 ,  0.15963862,  0.2486454 ],
       [ 0.93388875,  0.88004868,  0.05168671,  0.10246419,  0.58041918,
         0.58615098,  0.14136623,  0.81357534,  0.20479926,  0.06100231],
       [ 0.37678814,  0.44860367,  0.8325815 ,  0.65521957,  0.19530743,
         0.83521679,  0.34370679,  0.1311378 ,  0.49356478,  0.22003134],
       [ 0.804413  ,  0.00636037,  0.07989355,  0.32110333,  0.83551862,
         0.84964655,  0.70137205,  0.20316749,  0.97420252,  0.68687727],
       [ 0.93845529,  0.56982227,  0.46371859,  0.48322308,  0.58023376,
         0.16654531,  0.3534836 ,  0.52792953,  0.87952505,  0.77735686],
       [ 0.50281354,  0.14141083,  0.61086325,  0.73526305,  0.60019998,
         0.13039546,  0.68684811,  0.71639328,  0.54948654,  0.56435574],
       [ 0.98458032,  0.23176776,  0.83416003,  0.21097764,  0.26928483,
         0.0931104 ,  0.40533734,  0.04364528

Find the common items between a and b

In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=a[a==b]
c

array([2, 2, 4, 4])

Find the positions where elements of a and b match

In [28]:
c=np.where(a==b)
c

(array([1, 3, 5, 7]),)

Find all the values from array data where the values from array names are not equal to Will

In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
names[names!='Will']

array(['Bob', 'Joe', 'Bob', 'Joe', 'Joe'], 
      dtype='<U4')

# Difficulty Level Hard

Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [30]:
arr2d=np.arange(0,15)
arr2d.reshape((5,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [31]:
arr2d=np.arange(1,17)
arr2d.reshape(2,2,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [32]:
arr=np.linspace(0,4,10)
arr[arr<0.5]=0
np.sqrt(arr)


array([ 0.        ,  0.        ,  0.94280904,  1.15470054,  1.33333333,
        1.49071198,  1.63299316,  1.76383421,  1.88561808,  2.        ])

Find the unique names and sort them out!

In [33]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.sort(np.unique(names))

array(['Bob', 'Joe', 'Will'], 
      dtype='<U4')

From array a remove all items present in array b

In [34]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
c=np.array([])
for i in range(0,a.size):
    if a[i] not in b:
        np.delete(a,i)

a


array([1, 2, 3, 4, 5])

Following is the input NumPy array delete column two and insert following new column in its place.

In [35]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
newColumn=newColumn.reshape(3,1)
sampleArray=np.delete(sampleArray,1,axis=1)
np.append(sampleArray,newColumn,axis=1)


array([[34, 73, 10],
       [82, 12, 10],
       [53, 66, 10]])

Find the dot product of the above two matrix

In [45]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
y=y.reshape(2,3)
x*y

array([[  6.,  46.,  -3.],
       [ 28.,  40.,  54.]])

Generate a matrix of 20 random values and find its cumulative sum

In [49]:
arr=np.random.rand(20)
sum=0
for i in arr:
    sum+=i
sum

9.7459149433764711