In [2]:
import numpy as np

All of Alize’s recipes call for milk, eggs, sugar, flour, and butter. For example, her cupcake recipe calls for:


Flour Sugar Eggs Milk Butter 2 cups 0.75 cups 2 eggs 1 cups 0.5 cups Create a NumPy array that represents this data. Each element should be a number (i.e., 2 for “2 cups”). Save this array as cupcakes.

In [3]:
cupcakes=np.array([2.0, 0.75, 2.0, 1.0, 0.5])

Alize’s assistant has compiled all of her recipes into a csv (comma-separated variable) file called recipes.csv. Load this file into a variable called recipes.

In [4]:
recipes=np.genfromtxt('recipes.csv',delimiter=',')
recipes

array([[ 2.   ,  0.75 ,  2.   ,  1.   ,  0.5  ],
       [ 1.   ,  0.125,  1.   ,  1.   ,  0.125],
       [ 2.75 ,  1.5  ,  1.   ,  0.   ,  1.   ],
       [ 4.   ,  0.5  ,  2.   ,  2.   ,  0.5  ]])

4.Display recipes using print. Display recipes using print.

Each row represents a different recipe. Each column represents a different ingredient.

Recipe Cups of Flour Cups of Sugar Eggs Cups of Milk Cups of Butter

Cupcakes … … … … …

Pancake … … … … …

Cookie … … … … …

Bread … … … … …

In [5]:
Recipe=np.array(["Cupcakes","Pancake","Cookie","Bread"])
print("Recipe   Cups of Flour   Cups of Sugar   Eggs   Cups of Milk   Cups of Butter")
for i in range(Recipe.size):
    print("{} : {} {} {} {}".format(Recipe[i],recipes[i][0],recipes[i][1],recipes[i][2],recipes[i][3]))


Recipe   Cups of Flour   Cups of Sugar   Eggs   Cups of Milk   Cups of Butter
Cupcakes : 2.0 0.75 2.0 1.0
Pancake : 1.0 0.125 1.0 1.0
Cookie : 2.75 1.5 1.0 0.0
Bread : 4.0 0.5 2.0 2.0


In [6]:
eggs=recipes[:,3]
eggs

array([ 1.,  1.,  0.,  2.])

6.Which recipes require exactly 1 egg? Use a logical statement to get True or False for each value of eggs.

In [7]:
Recipe[recipes[:,3]==1.0]

array(['Cupcakes', 'Pancake'], 
      dtype='<U8')

7.Alize is going to make 2 batches of cupcakes (1st row) and 1 batch of cookies (3rd row).

You already have a variable for cupcakes. Create a variable for cookies with the data from the 3rd row.

In [7]:
cookies=recipes[3]


Get the number of ingredients for a double batch of cupcakes by using multiplication on cupcakes. Save your new variable to double_batch.

In [8]:
double_batch=np.power(cupcakes,2)
double_batch

array([ 4.    ,  0.5625,  4.    ,  1.    ,  0.25  ])

 Create a new variable called grocery_list by adding cookies and double_batch.

In [13]:
grocery_list=double_batch+cookies
grocery_list

array([ 8.    ,  1.0625,  6.    ,  3.    ,  0.75  ])